### ISSUE TITLE
Choose frameworks for client-side

### ISSUE THREAD

**Issue by iamacoderguy** [iamacoderguy/projectA#24]
- [x] Able to develop cross-platform applications (at least Android + iOS, or at most Android + iOS + Web + Desktop)
- [x] Relate to JS is an advantage
- [x] Convenient to write and execute unit tests, UI component tests, integration tests, etc.
- [x] Convenient to integrate and deliver
- [x] Wide-range applications/usages

**Comment by luyendt** [comment]
React Native

- React Native is a framework for building native applications using JavaScript
- For building mobile app (android, iOS) and web.
- Testing tool; there are some fast and safe tool(https://medium.com/@ronak8036/react-native-testing-tools-f38d715adb57), two of them are:
    + Using Jest frameworks for unit testing, integration testing and code coverage 
    + Using Detox for end-to-end testing
- Many CI/CD tools support React Native: Visual App center, CircleCI, Bitrise, Nevercode﻿,.. https://hackernoon.com/top-ci-cd-tools-for-your-android-and-ios-projects-8d356b983b3b
- React Native is used by reputed brands: Instagram, Facebook, Whatsapp, Dropbox, Netflix,...

React Native is the right fit for your app project when:-

- Your team has expertise in HTML, CSS and JavaScript.
- You need a highly customized specific app
( using variable states – dynamic inputs, active/inactive navigation items, buttons enabled/disabled, user login and access permissions, etc.)
- You need an app with multiple events
- You create a shareable components in app project
- You wish spend time on pre-development preparation

**Comment by luyendt** [comment]
Compare React Native vs Angular
https://appinventiv.com/blog/react-vs-angular/

recap:
- React is faster than angular since it relies upon Virtual DOM (while Angular uses real DOM).
- React is far easier to learn.
- React has a diverse and vibrant environment that provides developers with the flexibility to create your applications. This makes it more popular than Angular

Angular;
- Angular is a superheroic JavaScript MVVM framework, which is awesome for building highly interactive web applications.
- you could use NativeScript with Angular to build mobile apps.
https://docs.nativescript.org/angular/code-sharing/intro

When to choose Angular:
- You know Java, C# and previous of Angular
- You need a large-scale feature-rich application
- You embrace ready-to-use solutions and need higher productivity
- You wish to regulate app size
- App complexity lies from Low to Medium level

**Comment by luyendt** [comment]
Compare React Native vs Angular
https://appinventiv.com/blog/react-vs-angular/
recap:
- React is faster than angular since it relies upon Virtual DOM (while Angular uses real DOM).
- React is far easier to learn.
- React has a diverse and vibrant environment that provides developers with the flexibility to create your applications. This makes it more popular than Angular

**Comment by iamacoderguy** [comment]
We will choose React Native for client-side (mobile + web).
